/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardAgendaRouteImport } from './routes/_authenticated/dashboard.agenda'
import { Route as AuthenticatedDashboardConfiguracoesRouteImport } from './routes/_authenticated/dashboard.configuracoes'
import { Route as AuthenticatedDashboardEquipamentosRouteImport } from './routes/_authenticated/dashboard.equipamentos'
import { Route as AuthenticatedDashboardEstoqueRouteImport } from './routes/_authenticated/dashboard.estoque'
import { Route as AuthenticatedDashboardFinanceiroRouteImport } from './routes/_authenticated/dashboard.financeiro'
import { Route as AuthenticatedDashboardGarantiasRouteImport } from './routes/_authenticated/dashboard.garantias'
import { Route as AuthenticatedDashboardGastosRouteImport } from './routes/_authenticated/dashboard.gastos'
import { Route as AuthenticatedDashboardImportarClientesRouteImport } from './routes/_authenticated/dashboard.importar-clientes'
import { Route as AuthenticatedDashboardIntegracoesRouteImport } from './routes/_authenticated/dashboard.integracoes'
import { Route as AuthenticatedDashboardInteracoesRouteImport } from './routes/_authenticated/dashboard.interacoes'
import { Route as AuthenticatedDashboardKanbanRouteImport } from './routes/_authenticated/dashboard.kanban'
import { Route as AuthenticatedDashboardManutencoesRouteImport } from './routes/_authenticated/dashboard.manutencoes'
import { Route as AuthenticatedDashboardMigracaoRouteImport } from './routes/_authenticated/dashboard.migracao'
import { Route as AuthenticatedDashboardNotificacoesRouteImport } from './routes/_authenticated/dashboard.notificacoes'
import { Route as AuthenticatedDashboardOrdensRouteImport } from './routes/_authenticated/dashboard.ordens'
import { Route as AuthenticatedDashboardPermissoesRouteImport } from './routes/_authenticated/dashboard.permissoes'
import { Route as AuthenticatedDashboardRelatoriosRouteImport } from './routes/_authenticated/dashboard.relatorios'
import { Route as AuthenticatedDashboardTarefasRouteImport } from './routes/_authenticated/dashboard.tarefas'
import { Route as AuthenticatedDashboardUsuariosRouteImport } from './routes/_authenticated/dashboard.usuarios'
import { Route as AuthenticatedDashboardClientesIndexRouteImport } from './routes/_authenticated/dashboard.clientes.index'
import { Route as AuthenticatedDashboardClientesIdRouteImport } from './routes/_authenticated/dashboard.clientes.$id'
import { Route as AuthenticatedDashboardClientesQualidadeRouteImport } from './routes/_authenticated/dashboard.clientes.qualidade'
import { Route as AuthenticatedDashboardTecnicosIndexRouteImport } from './routes/_authenticated/dashboard.tecnicos.index'
import { Route as AuthenticatedDashboardTecnicosIdRouteImport } from './routes/_authenticated/dashboard.tecnicos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAgendaRoute =
  AuthenticatedDashboardAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardConfiguracoesRoute =
  AuthenticatedDashboardConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEquipamentosRoute =
  AuthenticatedDashboardEquipamentosRouteImport.update({
    id: '/equipamentos',
    path: '/equipamentos',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEstoqueRoute =
  AuthenticatedDashboardEstoqueRouteImport.update({
    id: '/estoque',
    path: '/estoque',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFinanceiroRoute =
  AuthenticatedDashboardFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGarantiasRoute =
  AuthenticatedDashboardGarantiasRouteImport.update({
    id: '/garantias',
    path: '/garantias',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGastosRoute =
  AuthenticatedDashboardGastosRouteImport.update({
    id: '/gastos',
    path: '/gastos',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardImportarClientesRoute =
  AuthenticatedDashboardImportarClientesRouteImport.update({
    id: '/importar-clientes',
    path: '/importar-clientes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIntegracoesRoute =
  AuthenticatedDashboardIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardInteracoesRoute =
  AuthenticatedDashboardInteracoesRouteImport.update({
    id: '/interacoes',
    path: '/interacoes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardKanbanRoute =
  AuthenticatedDashboardKanbanRouteImport.update({
    id: '/kanban',
    path: '/kanban',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardManutencoesRoute =
  AuthenticatedDashboardManutencoesRouteImport.update({
    id: '/manutencoes',
    path: '/manutencoes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMigracaoRoute =
  AuthenticatedDashboardMigracaoRouteImport.update({
    id: '/migracao',
    path: '/migracao',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNotificacoesRoute =
  AuthenticatedDashboardNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOrdensRoute =
  AuthenticatedDashboardOrdensRouteImport.update({
    id: '/ordens',
    path: '/ordens',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPermissoesRoute =
  AuthenticatedDashboardPermissoesRouteImport.update({
    id: '/permissoes',
    path: '/permissoes',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRelatoriosRoute =
  AuthenticatedDashboardRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTarefasRoute =
  AuthenticatedDashboardTarefasRouteImport.update({
    id: '/tarefas',
    path: '/tarefas',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUsuariosRoute =
  AuthenticatedDashboardUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardClientesIndexRoute =
  AuthenticatedDashboardClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardClientesIdRoute =
  AuthenticatedDashboardClientesIdRouteImport.update({
    id: '/clientes/$id',
    path: '/clientes/$id',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardClientesQualidadeRoute =
  AuthenticatedDashboardClientesQualidadeRouteImport.update({
    id: '/clientes/qualidade',
    path: '/clientes/qualidade',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTecnicosIndexRoute =
  AuthenticatedDashboardTecnicosIndexRouteImport.update({
    id: '/tecnicos/',
    path: '/tecnicos/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTecnicosIdRoute =
  AuthenticatedDashboardTecnicosIdRouteImport.update({
    id: '/tecnicos/$id',
    path: '/tecnicos/$id',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/agenda': typeof AuthenticatedDashboardAgendaRoute
  '/dashboard/configuracoes': typeof AuthenticatedDashboardConfiguracoesRoute
  '/dashboard/equipamentos': typeof AuthenticatedDashboardEquipamentosRoute
  '/dashboard/estoque': typeof AuthenticatedDashboardEstoqueRoute
  '/dashboard/financeiro': typeof AuthenticatedDashboardFinanceiroRoute
  '/dashboard/garantias': typeof AuthenticatedDashboardGarantiasRoute
  '/dashboard/gastos': typeof AuthenticatedDashboardGastosRoute
  '/dashboard/importar-clientes': typeof AuthenticatedDashboardImportarClientesRoute
  '/dashboard/integracoes': typeof AuthenticatedDashboardIntegracoesRoute
  '/dashboard/interacoes': typeof AuthenticatedDashboardInteracoesRoute
  '/dashboard/kanban': typeof AuthenticatedDashboardKanbanRoute
  '/dashboard/manutencoes': typeof AuthenticatedDashboardManutencoesRoute
  '/dashboard/migracao': typeof AuthenticatedDashboardMigracaoRoute
  '/dashboard/notificacoes': typeof AuthenticatedDashboardNotificacoesRoute
  '/dashboard/ordens': typeof AuthenticatedDashboardOrdensRoute
  '/dashboard/permissoes': typeof AuthenticatedDashboardPermissoesRoute
  '/dashboard/relatorios': typeof AuthenticatedDashboardRelatoriosRoute
  '/dashboard/tarefas': typeof AuthenticatedDashboardTarefasRoute
  '/dashboard/usuarios': typeof AuthenticatedDashboardUsuariosRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/clientes/$id': typeof AuthenticatedDashboardClientesIdRoute
  '/dashboard/clientes/qualidade': typeof AuthenticatedDashboardClientesQualidadeRoute
  '/dashboard/tecnicos/$id': typeof AuthenticatedDashboardTecnicosIdRoute
  '/dashboard/clientes/': typeof AuthenticatedDashboardClientesIndexRoute
  '/dashboard/tecnicos/': typeof AuthenticatedDashboardTecnicosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/agenda': typeof AuthenticatedDashboardAgendaRoute
  '/dashboard/configuracoes': typeof AuthenticatedDashboardConfiguracoesRoute
  '/dashboard/equipamentos': typeof AuthenticatedDashboardEquipamentosRoute
  '/dashboard/estoque': typeof AuthenticatedDashboardEstoqueRoute
  '/dashboard/financeiro': typeof AuthenticatedDashboardFinanceiroRoute
  '/dashboard/garantias': typeof AuthenticatedDashboardGarantiasRoute
  '/dashboard/gastos': typeof AuthenticatedDashboardGastosRoute
  '/dashboard/importar-clientes': typeof AuthenticatedDashboardImportarClientesRoute
  '/dashboard/integracoes': typeof AuthenticatedDashboardIntegracoesRoute
  '/dashboard/interacoes': typeof AuthenticatedDashboardInteracoesRoute
  '/dashboard/kanban': typeof AuthenticatedDashboardKanbanRoute
  '/dashboard/manutencoes': typeof AuthenticatedDashboardManutencoesRoute
  '/dashboard/migracao': typeof AuthenticatedDashboardMigracaoRoute
  '/dashboard/notificacoes': typeof AuthenticatedDashboardNotificacoesRoute
  '/dashboard/ordens': typeof AuthenticatedDashboardOrdensRoute
  '/dashboard/permissoes': typeof AuthenticatedDashboardPermissoesRoute
  '/dashboard/relatorios': typeof AuthenticatedDashboardRelatoriosRoute
  '/dashboard/tarefas': typeof AuthenticatedDashboardTarefasRoute
  '/dashboard/usuarios': typeof AuthenticatedDashboardUsuariosRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/clientes/$id': typeof AuthenticatedDashboardClientesIdRoute
  '/dashboard/clientes/qualidade': typeof AuthenticatedDashboardClientesQualidadeRoute
  '/dashboard/tecnicos/$id': typeof AuthenticatedDashboardTecnicosIdRoute
  '/dashboard/clientes': typeof AuthenticatedDashboardClientesIndexRoute
  '/dashboard/tecnicos': typeof AuthenticatedDashboardTecnicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/agenda': typeof AuthenticatedDashboardAgendaRoute
  '/_authenticated/dashboard/configuracoes': typeof AuthenticatedDashboardConfiguracoesRoute
  '/_authenticated/dashboard/equipamentos': typeof AuthenticatedDashboardEquipamentosRoute
  '/_authenticated/dashboard/estoque': typeof AuthenticatedDashboardEstoqueRoute
  '/_authenticated/dashboard/financeiro': typeof AuthenticatedDashboardFinanceiroRoute
  '/_authenticated/dashboard/garantias': typeof AuthenticatedDashboardGarantiasRoute
  '/_authenticated/dashboard/gastos': typeof AuthenticatedDashboardGastosRoute
  '/_authenticated/dashboard/importar-clientes': typeof AuthenticatedDashboardImportarClientesRoute
  '/_authenticated/dashboard/integracoes': typeof AuthenticatedDashboardIntegracoesRoute
  '/_authenticated/dashboard/interacoes': typeof AuthenticatedDashboardInteracoesRoute
  '/_authenticated/dashboard/kanban': typeof AuthenticatedDashboardKanbanRoute
  '/_authenticated/dashboard/manutencoes': typeof AuthenticatedDashboardManutencoesRoute
  '/_authenticated/dashboard/migracao': typeof AuthenticatedDashboardMigracaoRoute
  '/_authenticated/dashboard/notificacoes': typeof AuthenticatedDashboardNotificacoesRoute
  '/_authenticated/dashboard/ordens': typeof AuthenticatedDashboardOrdensRoute
  '/_authenticated/dashboard/permissoes': typeof AuthenticatedDashboardPermissoesRoute
  '/_authenticated/dashboard/relatorios': typeof AuthenticatedDashboardRelatoriosRoute
  '/_authenticated/dashboard/tarefas': typeof AuthenticatedDashboardTarefasRoute
  '/_authenticated/dashboard/usuarios': typeof AuthenticatedDashboardUsuariosRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/clientes/$id': typeof AuthenticatedDashboardClientesIdRoute
  '/_authenticated/dashboard/clientes/qualidade': typeof AuthenticatedDashboardClientesQualidadeRoute
  '/_authenticated/dashboard/tecnicos/$id': typeof AuthenticatedDashboardTecnicosIdRoute
  '/_authenticated/dashboard/clientes/': typeof AuthenticatedDashboardClientesIndexRoute
  '/_authenticated/dashboard/tecnicos/': typeof AuthenticatedDashboardTecnicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/agenda'
    | '/dashboard/configuracoes'
    | '/dashboard/equipamentos'
    | '/dashboard/estoque'
    | '/dashboard/financeiro'
    | '/dashboard/garantias'
    | '/dashboard/gastos'
    | '/dashboard/importar-clientes'
    | '/dashboard/integracoes'
    | '/dashboard/interacoes'
    | '/dashboard/kanban'
    | '/dashboard/manutencoes'
    | '/dashboard/migracao'
    | '/dashboard/notificacoes'
    | '/dashboard/ordens'
    | '/dashboard/permissoes'
    | '/dashboard/relatorios'
    | '/dashboard/tarefas'
    | '/dashboard/usuarios'
    | '/dashboard/'
    | '/dashboard/clientes/$id'
    | '/dashboard/clientes/qualidade'
    | '/dashboard/tecnicos/$id'
    | '/dashboard/clientes/'
    | '/dashboard/tecnicos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/agenda'
    | '/dashboard/configuracoes'
    | '/dashboard/equipamentos'
    | '/dashboard/estoque'
    | '/dashboard/financeiro'
    | '/dashboard/garantias'
    | '/dashboard/gastos'
    | '/dashboard/importar-clientes'
    | '/dashboard/integracoes'
    | '/dashboard/interacoes'
    | '/dashboard/kanban'
    | '/dashboard/manutencoes'
    | '/dashboard/migracao'
    | '/dashboard/notificacoes'
    | '/dashboard/ordens'
    | '/dashboard/permissoes'
    | '/dashboard/relatorios'
    | '/dashboard/tarefas'
    | '/dashboard/usuarios'
    | '/dashboard'
    | '/dashboard/clientes/$id'
    | '/dashboard/clientes/qualidade'
    | '/dashboard/tecnicos/$id'
    | '/dashboard/clientes'
    | '/dashboard/tecnicos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/agenda'
    | '/_authenticated/dashboard/configuracoes'
    | '/_authenticated/dashboard/equipamentos'
    | '/_authenticated/dashboard/estoque'
    | '/_authenticated/dashboard/financeiro'
    | '/_authenticated/dashboard/garantias'
    | '/_authenticated/dashboard/gastos'
    | '/_authenticated/dashboard/importar-clientes'
    | '/_authenticated/dashboard/integracoes'
    | '/_authenticated/dashboard/interacoes'
    | '/_authenticated/dashboard/kanban'
    | '/_authenticated/dashboard/manutencoes'
    | '/_authenticated/dashboard/migracao'
    | '/_authenticated/dashboard/notificacoes'
    | '/_authenticated/dashboard/ordens'
    | '/_authenticated/dashboard/permissoes'
    | '/_authenticated/dashboard/relatorios'
    | '/_authenticated/dashboard/tarefas'
    | '/_authenticated/dashboard/usuarios'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/clientes/$id'
    | '/_authenticated/dashboard/clientes/qualidade'
    | '/_authenticated/dashboard/tecnicos/$id'
    | '/_authenticated/dashboard/clientes/'
    | '/_authenticated/dashboard/tecnicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/agenda': {
      id: '/_authenticated/dashboard/agenda'
      path: '/agenda'
      fullPath: '/dashboard/agenda'
      preLoaderRoute: typeof AuthenticatedDashboardAgendaRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/configuracoes': {
      id: '/_authenticated/dashboard/configuracoes'
      path: '/configuracoes'
      fullPath: '/dashboard/configuracoes'
      preLoaderRoute: typeof AuthenticatedDashboardConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/equipamentos': {
      id: '/_authenticated/dashboard/equipamentos'
      path: '/equipamentos'
      fullPath: '/dashboard/equipamentos'
      preLoaderRoute: typeof AuthenticatedDashboardEquipamentosRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/estoque': {
      id: '/_authenticated/dashboard/estoque'
      path: '/estoque'
      fullPath: '/dashboard/estoque'
      preLoaderRoute: typeof AuthenticatedDashboardEstoqueRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/financeiro': {
      id: '/_authenticated/dashboard/financeiro'
      path: '/financeiro'
      fullPath: '/dashboard/financeiro'
      preLoaderRoute: typeof AuthenticatedDashboardFinanceiroRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/garantias': {
      id: '/_authenticated/dashboard/garantias'
      path: '/garantias'
      fullPath: '/dashboard/garantias'
      preLoaderRoute: typeof AuthenticatedDashboardGarantiasRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/gastos': {
      id: '/_authenticated/dashboard/gastos'
      path: '/gastos'
      fullPath: '/dashboard/gastos'
      preLoaderRoute: typeof AuthenticatedDashboardGastosRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/importar-clientes': {
      id: '/_authenticated/dashboard/importar-clientes'
      path: '/importar-clientes'
      fullPath: '/dashboard/importar-clientes'
      preLoaderRoute: typeof AuthenticatedDashboardImportarClientesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/integracoes': {
      id: '/_authenticated/dashboard/integracoes'
      path: '/integracoes'
      fullPath: '/dashboard/integracoes'
      preLoaderRoute: typeof AuthenticatedDashboardIntegracoesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/interacoes': {
      id: '/_authenticated/dashboard/interacoes'
      path: '/interacoes'
      fullPath: '/dashboard/interacoes'
      preLoaderRoute: typeof AuthenticatedDashboardInteracoesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/kanban': {
      id: '/_authenticated/dashboard/kanban'
      path: '/kanban'
      fullPath: '/dashboard/kanban'
      preLoaderRoute: typeof AuthenticatedDashboardKanbanRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/manutencoes': {
      id: '/_authenticated/dashboard/manutencoes'
      path: '/manutencoes'
      fullPath: '/dashboard/manutencoes'
      preLoaderRoute: typeof AuthenticatedDashboardManutencoesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/migracao': {
      id: '/_authenticated/dashboard/migracao'
      path: '/migracao'
      fullPath: '/dashboard/migracao'
      preLoaderRoute: typeof AuthenticatedDashboardMigracaoRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/notificacoes': {
      id: '/_authenticated/dashboard/notificacoes'
      path: '/notificacoes'
      fullPath: '/dashboard/notificacoes'
      preLoaderRoute: typeof AuthenticatedDashboardNotificacoesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/ordens': {
      id: '/_authenticated/dashboard/ordens'
      path: '/ordens'
      fullPath: '/dashboard/ordens'
      preLoaderRoute: typeof AuthenticatedDashboardOrdensRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/permissoes': {
      id: '/_authenticated/dashboard/permissoes'
      path: '/permissoes'
      fullPath: '/dashboard/permissoes'
      preLoaderRoute: typeof AuthenticatedDashboardPermissoesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/relatorios': {
      id: '/_authenticated/dashboard/relatorios'
      path: '/relatorios'
      fullPath: '/dashboard/relatorios'
      preLoaderRoute: typeof AuthenticatedDashboardRelatoriosRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/tarefas': {
      id: '/_authenticated/dashboard/tarefas'
      path: '/tarefas'
      fullPath: '/dashboard/tarefas'
      preLoaderRoute: typeof AuthenticatedDashboardTarefasRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/usuarios': {
      id: '/_authenticated/dashboard/usuarios'
      path: '/usuarios'
      fullPath: '/dashboard/usuarios'
      preLoaderRoute: typeof AuthenticatedDashboardUsuariosRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/clientes/': {
      id: '/_authenticated/dashboard/clientes/'
      path: '/clientes'
      fullPath: '/dashboard/clientes/'
      preLoaderRoute: typeof AuthenticatedDashboardClientesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/clientes/$id': {
      id: '/_authenticated/dashboard/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/dashboard/clientes/$id'
      preLoaderRoute: typeof AuthenticatedDashboardClientesIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/clientes/qualidade': {
      id: '/_authenticated/dashboard/clientes/qualidade'
      path: '/clientes/qualidade'
      fullPath: '/dashboard/clientes/qualidade'
      preLoaderRoute: typeof AuthenticatedDashboardClientesQualidadeRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/tecnicos/': {
      id: '/_authenticated/dashboard/tecnicos/'
      path: '/tecnicos'
      fullPath: '/dashboard/tecnicos/'
      preLoaderRoute: typeof AuthenticatedDashboardTecnicosIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/tecnicos/$id': {
      id: '/_authenticated/dashboard/tecnicos/$id'
      path: '/tecnicos/$id'
      fullPath: '/dashboard/tecnicos/$id'
      preLoaderRoute: typeof AuthenticatedDashboardTecnicosIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAgendaRoute: typeof AuthenticatedDashboardAgendaRoute
  AuthenticatedDashboardConfiguracoesRoute: typeof AuthenticatedDashboardConfiguracoesRoute
  AuthenticatedDashboardEquipamentosRoute: typeof AuthenticatedDashboardEquipamentosRoute
  AuthenticatedDashboardEstoqueRoute: typeof AuthenticatedDashboardEstoqueRoute
  AuthenticatedDashboardFinanceiroRoute: typeof AuthenticatedDashboardFinanceiroRoute
  AuthenticatedDashboardGarantiasRoute: typeof AuthenticatedDashboardGarantiasRoute
  AuthenticatedDashboardGastosRoute: typeof AuthenticatedDashboardGastosRoute
  AuthenticatedDashboardImportarClientesRoute: typeof AuthenticatedDashboardImportarClientesRoute
  AuthenticatedDashboardIntegracoesRoute: typeof AuthenticatedDashboardIntegracoesRoute
  AuthenticatedDashboardInteracoesRoute: typeof AuthenticatedDashboardInteracoesRoute
  AuthenticatedDashboardKanbanRoute: typeof AuthenticatedDashboardKanbanRoute
  AuthenticatedDashboardManutencoesRoute: typeof AuthenticatedDashboardManutencoesRoute
  AuthenticatedDashboardMigracaoRoute: typeof AuthenticatedDashboardMigracaoRoute
  AuthenticatedDashboardNotificacoesRoute: typeof AuthenticatedDashboardNotificacoesRoute
  AuthenticatedDashboardOrdensRoute: typeof AuthenticatedDashboardOrdensRoute
  AuthenticatedDashboardPermissoesRoute: typeof AuthenticatedDashboardPermissoesRoute
  AuthenticatedDashboardRelatoriosRoute: typeof AuthenticatedDashboardRelatoriosRoute
  AuthenticatedDashboardTarefasRoute: typeof AuthenticatedDashboardTarefasRoute
  AuthenticatedDashboardUsuariosRoute: typeof AuthenticatedDashboardUsuariosRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardClientesIdRoute: typeof AuthenticatedDashboardClientesIdRoute
  AuthenticatedDashboardClientesQualidadeRoute: typeof AuthenticatedDashboardClientesQualidadeRoute
  AuthenticatedDashboardTecnicosIdRoute: typeof AuthenticatedDashboardTecnicosIdRoute
  AuthenticatedDashboardClientesIndexRoute: typeof AuthenticatedDashboardClientesIndexRoute
  AuthenticatedDashboardTecnicosIndexRoute: typeof AuthenticatedDashboardTecnicosIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAgendaRoute: AuthenticatedDashboardAgendaRoute,
    AuthenticatedDashboardConfiguracoesRoute:
      AuthenticatedDashboardConfiguracoesRoute,
    AuthenticatedDashboardEquipamentosRoute:
      AuthenticatedDashboardEquipamentosRoute,
    AuthenticatedDashboardEstoqueRoute: AuthenticatedDashboardEstoqueRoute,
    AuthenticatedDashboardFinanceiroRoute:
      AuthenticatedDashboardFinanceiroRoute,
    AuthenticatedDashboardGarantiasRoute: AuthenticatedDashboardGarantiasRoute,
    AuthenticatedDashboardGastosRoute: AuthenticatedDashboardGastosRoute,
    AuthenticatedDashboardImportarClientesRoute:
      AuthenticatedDashboardImportarClientesRoute,
    AuthenticatedDashboardIntegracoesRoute:
      AuthenticatedDashboardIntegracoesRoute,
    AuthenticatedDashboardInteracoesRoute:
      AuthenticatedDashboardInteracoesRoute,
    AuthenticatedDashboardKanbanRoute: AuthenticatedDashboardKanbanRoute,
    AuthenticatedDashboardManutencoesRoute:
      AuthenticatedDashboardManutencoesRoute,
    AuthenticatedDashboardMigracaoRoute: AuthenticatedDashboardMigracaoRoute,
    AuthenticatedDashboardNotificacoesRoute:
      AuthenticatedDashboardNotificacoesRoute,
    AuthenticatedDashboardOrdensRoute: AuthenticatedDashboardOrdensRoute,
    AuthenticatedDashboardPermissoesRoute:
      AuthenticatedDashboardPermissoesRoute,
    AuthenticatedDashboardRelatoriosRoute:
      AuthenticatedDashboardRelatoriosRoute,
    AuthenticatedDashboardTarefasRoute: AuthenticatedDashboardTarefasRoute,
    AuthenticatedDashboardUsuariosRoute: AuthenticatedDashboardUsuariosRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardClientesIdRoute:
      AuthenticatedDashboardClientesIdRoute,
    AuthenticatedDashboardClientesQualidadeRoute:
      AuthenticatedDashboardClientesQualidadeRoute,
    AuthenticatedDashboardTecnicosIdRoute:
      AuthenticatedDashboardTecnicosIdRoute,
    AuthenticatedDashboardClientesIndexRoute:
      AuthenticatedDashboardClientesIndexRoute,
    AuthenticatedDashboardTecnicosIndexRoute:
      AuthenticatedDashboardTecnicosIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
